app:
  name: SuiviFactu
  description: Suivi des facturations
  version: 0.1.0
  termsOfServiceUrl: http://www.github.com/jntakpe/SuiviFactu
  contact: j.ntakpe@gmail.com
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
management:
  context-path: /manage
  security:
    enabled: false
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    database: postgresql
    openInView: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.format_sql: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  thymeleaf:
    prefix: classpath:/mails/
authentication:
    oauth:
        clientId: suivifactu
        secret: suivifactusupersecuresecret
        tokenValidityInSeconds: 1800
async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
---
spring:
  profiles: dev
datasource:
  url: jdbc:postgresql://localhost:5432/sf
  username: postgres
  password: sopra*
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
server:
  contextPath: /suivifactu
mail:
  host: smtp.gmail.com
  port: 587
  from: suivifactu@gmail.com
  username: suivifactu@gmail.com
  password: suivifactusupersecurepassword
  protocol: smtp
  tls: true
  auth: true
